// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcuxzuabtcfizsaradeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdXh6dWFidGNmaXpzYXJhZGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTMzOTYsImV4cCI6MjA2Mjk4OTM5Nn0.bv-6wjp7XhSjaGdnPl3gDJVgT82gxTjFw-22RTBULn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);